# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in sorcery_tcg_data_ruby.gemspec
gemspec path: "../../"

gem "rake", "~> 13.0"
gem "minitest", "~> 5.0"
gem "debug"