# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in sorcery_tcg_data_ruby.gemspec
gemspec path: "../../"

gem "debug"
gem "rake", "~> 13.0"
gem "realms_ruby_style", git: "https://github.com/realmsapp/realms_ruby_style", branch: "main"
